### ISSUE TITLE
choose language menu

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr-site#11]
where and how will we present the change language option on the website?
Most websites have it in the footer. The problem is most people that don't read english won't even look for language. Is it possible to have google point to the right version of the website based on your region? This also sucks, I hate translations and always prefer original, but I'm thinking about all those chinese and russians...

If we could find an elegant way to leave the drop down menu with all the languages on the top bar, it would be nice.

**Comment by dllud** [comment]
It will be automatic depending on the browser language (not on IP). Browser language is the best option. 

The language selection dropdown will be on the header menu, we will find space for it.

**Comment by cicardia** [comment]
perfecto!
