### ISSUE TITLE
Screenshots too small

### ISSUE THREAD

**Issue by dllud** [andrefbsantos/boilr-site#15]
"Features" should be almost touching the top bar and the navigation buttons should be touching the bottom.

![screenshots-small](https://cloud.githubusercontent.com/assets/1716156/6545846/fe59550a-c592-11e4-9509-23e24d094f09.png)

**Comment by cicardia** [comment]
I don't agree. when previewing the website, it felt the screenshot was too big. this should fit comfortably leaving space for an all around frame around the screenshot and still be able to read the text. specially on the mobile version.

**Comment by andrefbsantos** [comment]
Fixed in 813696caa9241cbc72cbe09ba74d76ea32a98ed4
