### ISSUE TITLE
Font - mail list

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr-site#19]
could you please replace the font for:

1. Futura
2. Helvetica
3. http://www.dafont.com/pt/dk-lemon-yellow-sun.font

please post the screenshots here.

**Comment by andrefbsantos** [comment]
Futura
![2015-03-12-135751_1366x768_scrot](https://cloud.githubusercontent.com/assets/7232385/6619140/25ab7f72-c8c0-11e4-993d-99d0a2b1ef68.png)

Helvetica
![2015-03-12-135807_1366x768_scrot](https://cloud.githubusercontent.com/assets/7232385/6619149/3f687adc-c8c0-11e4-8721-1a92ce325bf9.png)

**Comment by cicardia** [comment]
what about this font? - http://www.dafont.com/pt/dk-lemon-yellow-sun.font
it was suggested by a designer.

I think futura is inadequate. what was the original font?

**Comment by andrefbsantos** [comment]
Lemon Yellow Sun requires a license for non personal use. Can you find a similar font with a different license?

**Comment by cicardia** [comment]
nevermind. either helvetica or the one we had in the beginning

**Comment by andrefbsantos** [comment]
The one in the beginning was Helvetica.

**Comment by cicardia** [comment]
lets keep that one, just check if bold reads a bit better ;)
