### ISSUE TITLE
mail list/newsletter

### ISSUE THREAD

**Issue by algazarra** [andrefbsantos/boilr-site#3]
we should have a mail list on the website's header or anywhere on the top

something simple like:
"sign up for:
news, updates, promotions"

**Comment by dllud** [comment]
Better: Boilr is beta software. Sign our newsletter to get version updates and other news.

**Comment by cicardia** [comment]
Boilr is beta. Sign our newsletter for  news, updates and promos.

**Comment by dllud** [comment]
"Boilr is beta." means nothing. Better: Boilr is still beta. OR Boilr is in beta.

**Comment by dllud** [comment]
Working on the master branch.
