### ISSUE TITLE
list of supported exchanges & coins

### ISSUE THREAD

**Issue by algazarra** [andrefbsantos/boilr-site#9]
the site needs to show a list of the supported exchanges & coins. also useful regarding SEO

**Comment by dllud** [comment]
Yup, planned since your request. It is also going to be use as a way to showcase libdynticker in action.

**Comment by andrefbsantos** [comment]
And the list/grid of exchanges would be inside which section?

**Comment by cicardia** [comment]
correct me if i'm wrong. The updated website will be something like:
1. top bar (with navigation links + social icons & links to the right, no need for a whole section)
2. video intro + mail list
3. features slideshow (mockup)
4. supported exchange & coins (searchable/filterable & linking to exchange/coin website/ANN page
5. download&fork
6. similar apps
7. Donate

**Comment by dllud** [comment]
Agree. Although the links to exchange/coin will only be added when doing the same in Boilr.
